version: '3'

services:
  backend-svc:
    image: weiqinghuang/guts_api_demo:0.1
    deploy:
      replicas: 2
      endpoint_mode: vip
      mode: replicated
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
    container_name: backend-api
    ports:
      - 5000:5000