apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guts-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guts-demo
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75